# Generated by Django 3.2.7 on 2021-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='external_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='ID пользователя'),
        ),
    ]
