# Generated by Django 3.2.7 on 2021-10-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_profilesettings_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='internal',
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='external_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', to_field='external_id', verbose_name='ID пользователя'),
        ),
    ]
