# Generated by Django 3.2.7 on 2021-10-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20211002_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64, verbose_name='API')),
                ('secret_key', models.CharField(max_length=64, verbose_name='SecretAPI')),
                ('subaccount_email', models.TextField(verbose_name='subaccount_email')),
                ('pool_username', models.TextField(verbose_name='pool_username')),
                ('external_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Настройки профиля',
                'verbose_name_plural': 'Настройки профиля',
            },
        ),
    ]
