# Generated by Django 3.2.7 on 2021-10-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20211002_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='external_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', verbose_name='ID пользователя'),
        ),
    ]
