# Generated by Django 3.2.7 on 2021-10-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_external_id_profilesettings_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesettings',
            old_name='user_id',
            new_name='user',
        ),
    ]
