# Generated by Django 3.2.7 on 2021-10-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_user_id_profilesettings_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesettings',
            old_name='user',
            new_name='internal',
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='external_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
    ]
