# Generated by Django 3.2.7 on 2021-10-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_profile_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID пользователя'),
        ),
    ]
