# Generated by Django 3.2.7 on 2021-10-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_profilesettings_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='ID пользователя'),
        ),
    ]
