# Generated by Django 3.2.7 on 2021-10-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_profilesettings_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='internal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', verbose_name='ID пользователя'),
        ),
    ]
