# Generated by Django 3.2.7 on 2021-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_rename_external_id_profilesettings_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='client',
            field=models.TextField(default=0, verbose_name='pool_username'),
            preserve_default=False,
        ),
    ]
