# Generated by Django 3.2.7 on 2021-10-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_profilesettings_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='client',
        ),
    ]
